### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by technomancy** [stefandevai/fennel-tic80-game#1]
Hello!

I was thinking about linking this from the Fennel wiki, but I had a few questions and ideas. First of all, this project assumes that you will compile ahead-of-time to Lua rather than using TIC's built-in Fennel support. It seems like the native support would be more useful for more folks. Do you think this project should support both?

I think the `utils.sh` script could be done more declaratively using a Makefile; would you like me to try that?

I have some work in process to allow exporting to HTML from the command-line here: https://github.com/nesbox/TIC-80/pull/1078 ... once I get that figured out, maybe we could add the option to publish directly to itch from the makefile (assuming butler is installed).

I also found it useful to have a `make check` target which could run the compiler on the source without launching TIC to check for typos and syntax errors; this can be integrated into editors like Emacs.

Thanks, and congrats again for your great work on Amethyst Waters.

**Comment by stefandevai** [comment]
Hello technomancy!

First of all, thanks for taking a look at the project. It was just my own boilerplate at the beginning of the jam, but I thought it was a good idea to share. I remember now that I should update the README with the tips you gave about starting a project.

I think your ideas are great and I agree with them. If you can contribute that would be awesome :)

I'll also polish the script I used to minify the code and include it in the project or as another one, maybe someone will find useful to minify fennel code outside TIC-80's context.

Thanks again and I hope there will be another Lisp Game Jam soon.
